### ISSUE TITLE
Measure total amount of bandwidth used by maintenance and other non experiment related tasks

### ISSUE THREAD

**Issue by jonakarl** [MONROE-PROJECT/Maintenance#1]
In the spirit of MONROE-PROJECT/Experiments#4 we should have a rough estimate of the total amount of bandwidth consumed by maintenance and other tasks related to have nodes up and running.

**Comment by relet** [comment]
We are monitoring the total bandwidth used in the host network namespace. I sent a traffic report earlier which still shows a lot of variance, due to the ongoing deployment and updates. 
What we could see is that we used 2-4 GB per interface on "idle" nodes, but that is just an order of magnitude, not a final number. It currently includes tasks like rsync of results and deployment which we will measure separately.
